# Generated by Django 4.0.6 on 2022-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_criacao_url_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlredirect',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
