name : GitHub action for urlreduce

on: [pull request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pipenv==2018.11.26
          pipenv sync --dev
      - name: Run pytest
        run: |
          pytest
