name : GitHub action for urlreduce

on: [ pull_request ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
      - name: Lint com Flake8
        run: |
          flake8
      - name: Testes de aplicação com Pytest
        run: |
          python -m pytest
      - name: Report coverage to codecov
        uses: codecov/codecov-action@v3
